/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package musicstore.vista;
import musicstore.modelo.Usuario;
import musicstore.persistencia.Data;
import musicstore.servicio.UsuarioServicio;
import javax.swing.JOptionPane;

public class FrmLogin extends javax.swing.JFrame {

    private Data data;
    private UsuarioServicio usuarioServicio;
    
    public FrmLogin(Data data) {
        
        initComponents();
        this.data = data;
        this.usuarioServicio = new UsuarioServicio(data);
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloPrincipal = new javax.swing.JLabel();
        tituloSecundario = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblPsw = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPsw = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MusicStore");
        setResizable(false);

        tituloPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloPrincipal.setText("MusicStore");
        tituloPrincipal.setName("LblTitulo"); // NOI18N

        tituloSecundario.setText("Iniciar Sesión");
        tituloSecundario.setName("LblTituloDos"); // NOI18N

        lblUsuario.setText("Usuario");
        lblUsuario.setName("lblUsuario"); // NOI18N

        lblPsw.setText("Contraseña");
        lblPsw.setName("lblPsw"); // NOI18N

        txtUsuario.setName("txtUsuario"); // NOI18N

        txtPsw.setName("txtPsw"); // NOI18N

        btnIngresar.setText("Ingresar");
        btnIngresar.setName("btnIngresar"); // NOI18N
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPsw)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario)
                    .addComponent(txtPsw, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(tituloSecundario))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(149, 149, 149))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(tituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloSecundario)
                .addGap(33, 33, 33)
                .addComponent(lblUsuario)
                .addGap(18, 18, 18)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblPsw)
                .addGap(18, 18, 18)
                .addComponent(txtPsw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIngresar)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        
        // Obtener los datos ingresados por el usuario
       String nombreUsuario = txtUsuario.getText();
       String password = new String(txtPsw.getPassword());
       
          // Validar que ambos campos estén completos
       if (nombreUsuario.isBlank() || password.isBlank()) {

        JOptionPane.showMessageDialog(this, "Debe completar el usuario y la contraseña.",
                "Campos obligatorios",
                JOptionPane.WARNING_MESSAGE);
         // Finalizar el método si falta información
        return;
    }
       
       Usuario usuario = usuarioServicio.validarLogin(nombreUsuario, password);
       
           // Validar las credenciales mediante la capa de servicios
       if(usuario != null){
           FrmPrincipal principal = new FrmPrincipal(data, usuario);
            principal.setVisible(true);

              // Cerrar la ventana de Login
            dispose();
       }else {
            // Informar que las credenciales son incorrectas
        JOptionPane.showMessageDialog(
                this,
                "Usuario o contraseña incorrectos.",
                "Error de autenticación",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnIngresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel lblPsw;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel tituloPrincipal;
    private javax.swing.JLabel tituloSecundario;
    private javax.swing.JPasswordField txtPsw;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
